POST http://localhost:5000/user/forgot-password/sendmail
Content-Type: application/json

{
    "email": "sensouvik51@gmail.com"
}


###
PUT http://localhost:5000/user/forgot-password/update-password/6155c1f68fbc390ba9b75a25
Content-Type: application/json

{
    "password": "hellothere"
}