POST http://localhost:5000/user-account/signup
Content-Type: application/json

{
    "username":"souvik",
    "email": "sensouvik51@gmail.com",
    "password": "souvik11sen"
}
###

POST http://localhost:5000/user-account/login
Content-Type: application/json

{
    "email":"sensouvik51@gmail.com",
    "password":"souvik11sen"
}

###

GET http://localhost:5000/user-account
Content-Type: application/json



###

DELETE http://localhost:5000/useAccount/6155c0aa8fbc390ba9b75a19
Content-Type: application/json

###

PUT http://localhost:5000/user-account/account-activation/62a38f84a5c96007741d6e07
Content-Type: application/json



